name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '16'
  
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Build & Deploy Remix App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          app_build_command: "npm run build:app"
          skip_api_build: true
          api_location: "api" # Api source code path - optional
          api_build_command: "npm run build:api --if-present"
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          
      - name: Build Remix Server Function
        id: remixserver
        run: |
          pushd './api'
          npm install
          npm run build
          popd
          
      - name: 'Run Azure Functions Action'
        run: echo Deploy Azure Function here
        #uses: Azure/functions-action@v1
        #id: fa
        #with:
        #  app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        #  slot-name: 'Production'
        #  package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        #  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_95656BAE3237414EB45CE714883E0DCD }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
